#----------------------------------------------------------
#--  HACK: Gestures
#----------------------------------------------------------

gestures {
    # Basic swiping logic
    workspace_swipe_distance = 500
    workspace_swipe_invert = true
    workspace_swipe_forever = true
    workspace_swipe_cancel_ratio = 0.15

    # Workspace switching
    gesture = 4, horizontal, mod:SUPER, scale:0.8, workspace

    # Open kitty
    gesture = 3, up, mod:SUPER, dispatcher, exec, kitty

    # windows control
    gesture = 4, right, dispatcher, movefocus, l         # Focus left
    gesture = 4, left, dispatcher, movefocus, r          # Focus right
    gesture = 4, up, dispatcher, fullscreen, 0           # Toggle fullscreen
    gesture = 4, down, dispatcher, togglefloating        # Toggle floating
    gesture = 3, down, mod:SUPER, close                  # close window
    gesture = 3, swipe, move,                            # Move window
}

binds {
  workspace_back_and_forth = false
  allow_workspace_cycles = true
  pass_mouse_when_bound = false
}
