#----------------------------------------------------------
#--  HACK: Gestures
#----------------------------------------------------------

gestures {
    # Basic swiping logic
    workspace_swipe_distance = 500
    workspace_swipe_invert = true
    workspace_swipe_forever = true
    workspace_swipe_cancel_ratio = 0.15

    # Workspace switching
    gesture = 4, horizontal, scale:0.8, workspace

    # Move window
    # gesture = 3, swipe, move,

    # gesture = 3, up, mod:SUPER, dispatcher, exec, kitty

    # window
    gesture = 3, right, dispatcher, movefocus, l
    gesture = 3, left, dispatcher, movefocus, r
    gesture = 3, up, dispatcher, fullscreen, 0
    gesture = 3, down, dispatcher, togglefloating 
    gesture = 4, down, close
}

binds {
  workspace_back_and_forth = false
  allow_workspace_cycles = true
  pass_mouse_when_bound = false
}
