#----------------------------------------------------------
#--  HACK: Kitty border color based on neovim mode
#----------------------------------------------------------

$color_normal  = rgb(FFD766)
$color_insert  = rgb(A8DB75)
$color_replace = rgb(FF6187)
$color_visual  = rgb(AB9DF2)

windowrule {
    name = nvim-normal-border
    match:class = ^(kitty)$
    match:title = .*(nvim-normal).*
    border_color = $color_normal
}

windowrule {
    name = nvim-insert-border
    match:class = ^(kitty)$
    match:title = .*(nvim-insert).*
    border_color = $color_insert
}

windowrule {
    name = nvim-replace-border
    match:class = ^(kitty)$
    match:title = .*(nvim-replace).*
    border_color = $color_replace
}

windowrule {
    name = nvim-visual-border
    match:class = ^(kitty)$
    match:title = .*(nvim-visual).*
    border_color = $color_visual
}
